/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CreateServiceRouteImport } from './routes/create-service'
import { Route as CreatePostRouteImport } from './routes/create-post'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ServiceServiceIdRouteImport } from './routes/service.$serviceId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as ServiceServiceIdEditRouteImport } from './routes/service.$serviceId.edit'
import { Route as ProfileUserIdSettingsRouteImport } from './routes/profile.$userId.settings'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateServiceRoute = CreateServiceRouteImport.update({
  id: '/create-service',
  path: '/create-service',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePostRoute = CreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceServiceIdRoute = ServiceServiceIdRouteImport.update({
  id: '/service/$serviceId',
  path: '/service/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceServiceIdEditRoute = ServiceServiceIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ServiceServiceIdRoute,
} as any)
const ProfileUserIdSettingsRoute = ProfileUserIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileUserIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/create-post': typeof CreatePostRoute
  '/create-service': typeof CreateServiceRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRouteWithChildren
  '/service/$serviceId': typeof ServiceServiceIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/$userId/settings': typeof ProfileUserIdSettingsRoute
  '/service/$serviceId/edit': typeof ServiceServiceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/create-post': typeof CreatePostRoute
  '/create-service': typeof CreateServiceRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRouteWithChildren
  '/service/$serviceId': typeof ServiceServiceIdRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/profile/$userId/settings': typeof ProfileUserIdSettingsRoute
  '/service/$serviceId/edit': typeof ServiceServiceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/create-post': typeof CreatePostRoute
  '/create-service': typeof CreateServiceRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRouteWithChildren
  '/service/$serviceId': typeof ServiceServiceIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/$userId/settings': typeof ProfileUserIdSettingsRoute
  '/service/$serviceId/edit': typeof ServiceServiceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/create-post'
    | '/create-service'
    | '/discover'
    | '/messages'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/messages/$conversationId'
    | '/post/$postId'
    | '/profile/$userId'
    | '/service/$serviceId'
    | '/dashboard/'
    | '/profile/$userId/settings'
    | '/service/$serviceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/create-post'
    | '/create-service'
    | '/discover'
    | '/messages'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/messages/$conversationId'
    | '/post/$postId'
    | '/profile/$userId'
    | '/service/$serviceId'
    | '/dashboard'
    | '/profile/$userId/settings'
    | '/service/$serviceId/edit'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/create-post'
    | '/create-service'
    | '/discover'
    | '/messages'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/messages/$conversationId'
    | '/post/$postId'
    | '/profile/$userId'
    | '/service/$serviceId'
    | '/dashboard/'
    | '/profile/$userId/settings'
    | '/service/$serviceId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  CreatePostRoute: typeof CreatePostRoute
  CreateServiceRoute: typeof CreateServiceRoute
  DiscoverRoute: typeof DiscoverRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  PostPostIdRoute: typeof PostPostIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRouteWithChildren
  ServiceServiceIdRoute: typeof ServiceServiceIdRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-service': {
      id: '/create-service'
      path: '/create-service'
      fullPath: '/create-service'
      preLoaderRoute: typeof CreateServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-post': {
      id: '/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof CreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$serviceId': {
      id: '/service/$serviceId'
      path: '/service/$serviceId'
      fullPath: '/service/$serviceId'
      preLoaderRoute: typeof ServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$serviceId/edit': {
      id: '/service/$serviceId/edit'
      path: '/edit'
      fullPath: '/service/$serviceId/edit'
      preLoaderRoute: typeof ServiceServiceIdEditRouteImport
      parentRoute: typeof ServiceServiceIdRoute
    }
    '/profile/$userId/settings': {
      id: '/profile/$userId/settings'
      path: '/settings'
      fullPath: '/profile/$userId/settings'
      preLoaderRoute: typeof ProfileUserIdSettingsRouteImport
      parentRoute: typeof ProfileUserIdRoute
    }
  }
}

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface ProfileUserIdRouteChildren {
  ProfileUserIdSettingsRoute: typeof ProfileUserIdSettingsRoute
}

const ProfileUserIdRouteChildren: ProfileUserIdRouteChildren = {
  ProfileUserIdSettingsRoute: ProfileUserIdSettingsRoute,
}

const ProfileUserIdRouteWithChildren = ProfileUserIdRoute._addFileChildren(
  ProfileUserIdRouteChildren,
)

interface ServiceServiceIdRouteChildren {
  ServiceServiceIdEditRoute: typeof ServiceServiceIdEditRoute
}

const ServiceServiceIdRouteChildren: ServiceServiceIdRouteChildren = {
  ServiceServiceIdEditRoute: ServiceServiceIdEditRoute,
}

const ServiceServiceIdRouteWithChildren =
  ServiceServiceIdRoute._addFileChildren(ServiceServiceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  CreatePostRoute: CreatePostRoute,
  CreateServiceRoute: CreateServiceRoute,
  DiscoverRoute: DiscoverRoute,
  MessagesRoute: MessagesRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  PostPostIdRoute: PostPostIdRoute,
  ProfileUserIdRoute: ProfileUserIdRouteWithChildren,
  ServiceServiceIdRoute: ServiceServiceIdRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
